### PR TITLE
BUILD: added support for amdclang-based build

### PR DESCRIPTION
**Pull request by nileshnegi**
## What
Adding support for clang-based build with ROCm 6.0 and above

## Why ?
AMD plans to switch from `hipcc` to `clang` as its default compiler for ROCm 6.0 and above.

### CODE REVIEW

**Comment by edgargabriel** [comment]
The error observed does not seem related to this pr

```
make[3]: Entering directory '/home/runner/work/ucc/ucc/src/components/cl/hier'
  CC       libucc_cl_hier_la-cl_hier.lo
cl_hier.c:62:6: error: incompatible pointer types initializing 'void (*)(ucs_string_buffer_t *, const void *)' with an expression of type 'char [94]' [-Werror,-Wincompatible-pointer-types]
     UCC_CONFIG_TYPE_PIPELINE_PARAMS},
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/ucc/ucc/src/utils/ucc_parser.h:287:13: note: expanded from macro 'UCC_CONFIG_TYPE_PIPELINE_PARAMS'
            "thresh=<memunit>:fragsize=<memunit>:nfrags="                      \
```

**Comment by edgargabriel** [comment]
I see that all other currently pending  pull requests have same error message, i.e. it is not related to this pr. However, interestingly I cannot reproduce that locally. I tried on two different machines and with multiple configurations, and UCC compiles correctly in all instances for me. So not sure what can trigger this error in the CI.

@manjugv  @Sergei-Lebedev If possible, this is the pr that we would love to see go into ucc 1.3. It took us a few days longer than expected, it was a bit trickier to resolve than we initially thought, but its there now and seems to work.

**Comment by Sergei-Lebedev** [comment]
> The error observed does not seem related to this pr
> 
> ```
> make[3]: Entering directory '/home/runner/work/ucc/ucc/src/components/cl/hier'
>   CC       libucc_cl_hier_la-cl_hier.lo
> cl_hier.c:62:6: error: incompatible pointer types initializing 'void (*)(ucs_string_buffer_t *, const void *)' with an expression of type 'char [94]' [-Werror,-Wincompatible-pointer-types]
>      UCC_CONFIG_TYPE_PIPELINE_PARAMS},
>      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/runner/work/ucc/ucc/src/utils/ucc_parser.h:287:13: note: expanded from macro 'UCC_CONFIG_TYPE_PIPELINE_PARAMS'
>             "thresh=<memunit>:fragsize=<memunit>:nfrags="                      \
> ```

Yes, it's unrelated. This happened due to another change in UCS here https://github.com/openucx/ucx/pull/9555.
Already fixed in UCC master

**Comment by edgargabriel** [comment]
@Sergei-Lebedev are you referring to https://github.com/openucx/ucc/pull/895 ? I *think* that is already included in this branch, see the git log history:

```
* b2cb8f1 (HEAD -> topic/amdclang-build, origin/topic/amdclang-build) BUILD: added support for amdclang-based build
* 2058f67 TL/UCP: reduce dbt (#888)
* 557978e CI: Update CUDA, MOFED & CI images (#894)
* d4d3393 TL/MLX5: fix port query (#897)
* 2ab6d07 TL/SHARP: Add reduce-scatter support (#891)
* 974605a TL/MLX5: add mcast helper functions (#880)
* 8c31870 BUILD: fix ucs parser set value (#895)
* 5142705 TL/NCCL: lazy init nccl comm (#851)
* e038288 TOOLS: use separate cuda alloc in perftest (#872)
* 7e22dde TEST: improve test output (#890)
...
```

**Comment by Sergei-Lebedev** [comment]
> @Sergei-Lebedev are you referring to #895 ? I _think_ that is already included in this branch, see the git log history:
> 
> ```
> * b2cb8f1 (HEAD -> topic/amdclang-build, origin/topic/amdclang-build) BUILD: added support for amdclang-based build
> * 2058f67 TL/UCP: reduce dbt (#888)
> * 557978e CI: Update CUDA, MOFED & CI images (#894)
> * d4d3393 TL/MLX5: fix port query (#897)
> * 2ab6d07 TL/SHARP: Add reduce-scatter support (#891)
> * 974605a TL/MLX5: add mcast helper functions (#880)
> * 8c31870 BUILD: fix ucs parser set value (#895)
> * 5142705 TL/NCCL: lazy init nccl comm (#851)
> * e038288 TOOLS: use separate cuda alloc in perftest (#872)
> * 7e22dde TEST: improve test output (#890)
> ...
> ```

No, it was part of https://github.com/openucx/ucc/pull/848, that we merged today.

File: cuda_lt.sh [hunk 1]
```diff
@@ -27,15 +27,21 @@ local_npic_filepath="${local_npic_dir}${o_filename}"
 mkdir -p $pic_dir
 
 tmpcmd="${@:3}"
-if [[ "$tmpcmd" == *"hipcc"* ]]; then
+if [[ "$tmpcmd" == *"amdclang"* ]]; then
+  cmd="${@:3:2} -x hip -target x86_64-unknown-linux-gnu --offload-arch=gfx908:xnack- --offload-arch=gfx90a:xnack- --offload-arch=gfx90a:xnack+ --offload-arch=gfx940 --offload-arch=gfx941 --offload-arch=gfx942 --offload-arch=gfx1030 --offload-arch=gfx1100 --offload-arch=gfx1101 --offload-arch=gfx1102 ${@:5} -fPIC -o ${pic_filepath}"
```
Comment (Sergei-Lebedev) [inline cuda_lt.sh:31]: does it make sense to allow user to specify what GPUs to support during configure?

**Review by Sergei-Lebedev — APPROVED** [review]

File: config/m4/rocm.m4 [hunk 2]
```diff
@@ -102,11 +102,36 @@ AS_IF([test "x$with_rocm" != "xno"],
...
+        ]], [[
+#if HIP_VERSION_MAJOR >= 6
+return 0;
+#else
+intr make+compilation_fail()
+#endif
+        ]])],
+        [ROCM_VERSION_60_OR_GREATER=1],
+        [ROCM_VERSION_60_OR_GREATER=0])
+
```
[the remark this answers is not in the document]
Comment (nileshnegi) [reply config/m4/rocm.m4:117]: done

File: cuda_lt.sh (hunk 1 above)
Comment (nileshnegi) [reply cuda_lt.sh]: for now, we'd prefer to leave it compiled for multiple GPUs... we might add this feature later

File: config/m4/rocm.m4 [hunk 3]
```diff
@@ -102,28 +119,25 @@ AS_IF([test "x$with_rocm" != "xno"],
...
+    CHECK_ROCM_VERSION(6, ROCM_VERSION_60_OR_GREATER)
+    AC_MSG_CHECKING([if ROCm version is 6.0 or above])
+    if test "$ROCM_VERSION_60_OR_GREATER" = "1" ; then
         AC_MSG_RESULT([yes])
     else
         AC_MSG_RESULT([no])
-        HIP_CPPFLAGS="${HIP_CPPFLAGS} -I${with_rocm}/hip/include"
-        HIP_LDFLAGS="${HIP_LDFLAGS} -L${with_rocm}/hip/lib"
+        # Check whether we run on ROCm 5.0-5.7
+        CHECK_ROCM_VERSION(5, 6, ROCM_VERSION_50_OR_GREATER)
```
Comment (Sergei-Lebedev) [inline config/m4/rocm.m4:132]: Should it be CHECK_ROCM_VERSION(5, ROCM_VERSION_50_OR_GREATER)?

Comment (nileshnegi) [reply config/m4/rocm.m4]: done

**Comment by nileshnegi** [comment]
@Sergei-Lebedev could you please re-review the latest change?
we added `--offload-arch=native` to support future GPU architectures in UCC v1.3

**Review by Sergei-Lebedev — APPROVED** [review]

**Comment by Sergei-Lebedev** [comment]
> @Sergei-Lebedev could you please re-review the latest change? we added `--offload-arch=native` to support future GPU architectures in UCC v1.3

LGTM. But in my opinion it's better to allow users to choose what arch to compile for since 
1. They can reduce compile time and binary size by choosing specific GPU arch
2. It won't work if compiling on a system without GPU for some GPU arch that's not listed in your PR.

Just something to consider for next release maybe.

**Comment by edgargabriel** [comment]
@Sergei-Lebedev you are absolutely correct, and it is on our to-do list. We just wanted to make sure that we do not miss the ucc 1.3 cut-off, since the pr is important for us, so we tried to keep the pr as simple as we could. (In addition, hipcc did underneath the hood the same thing, so this is not a regression, this is more like maintaining the status quo at the moment).

But we plant to fix this going forward for ucc 1.4
