### ISSUE TITLE
gcc 11.2 error: implicit conversion from ‘ucs_status_t’ to ‘ucc_status_t’

### ISSUE THREAD

**Issue by flx42** [openucx/ucc#329]
UCC fails to compile on Ubuntu 21.10 with gcc 11.2.0, as UCC sets `-Werror` and `-Wenum-conversion` in the CFLAGS:
```console
make[3]: Entering directory '/home/fabecassis/github/ucc/src/components/tl/sharp'
  CC       libucc_tl_sharp_la-tl_sharp_context.lo
tl_sharp_context.c: In function ‘ucc_tl_sharp_context_t_init’:
tl_sharp_context.c:285:15: error: implicit conversion from ‘ucs_status_t’ to ‘ucc_status_t’ [-Werror=enum-conversion]
  285 |        status = ucc_rcache_create(&rcache_params, "SHARP", NULL, &self->rcache);
      |               ^
cc1: all warnings being treated as errors
make[3]: *** [Makefile:582: libucc_tl_sharp_la-tl_sharp_context.lo] Error 1
  CC       libucc_tl_sharp_la-tl_sharp_coll.lo
tl_sharp_coll.c: In function ‘ucc_tl_sharp_mem_register’:
tl_sharp_coll.c:87:16: error: implicit conversion from ‘ucs_status_t’ to ‘ucc_status_t’ [-Werror=enum-conversion]
   87 |         status = ucc_rcache_get(ctx->rcache, (void *)addr, length,
      |                ^
cc1: all warnings being treated as errors
make[3]: *** [Makefile:596: libucc_tl_sharp_la-tl_sharp_coll.lo] Error 1
```

UCX comes from HPC-X 2.9.0:
```console
$ ucx_info -v
# UCT version=1.11.0 revision 6031c98
# configured with: --disable-logging --disable-debug --disable-assertions --disable-params-check --with-knem --with-xpmem=/hpc/local/oss/xpmem/90a95a4 --without-java --enable-devel-headers --with-cuda=/hpc/local/oss/cuda11.2 --with-gdrcopy --prefix=/build-result/hpcx-v2.9.0-gcc-MLNX_OFED_LINUX-5.4-1.0.3.0-ubuntu20.04-x86_64/ucx
```

The workaround is simple for now though: `make CFLAGS=-Wno-error=enum-conversion`
